# Welcome to ExactWorx!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ExactWorx
email: info@ExactWorx.com
description: > # this means to ignore newlines until "baseurl:"
  At ExactWorx, we empower businesses to serve their customers with greater precision, efficiency, and impact. 
  Specializing in technology-driven solutions, we take an innovative approach to communication and management;
  helping organizations streamline operations, strengthen client engagement, 
  and stay ahead in a rapidly evolving digital landscape.
  
  Whether you're in construction, home services, business support, or technology consulting, 
  our tailored solutions are designed to meet your exact needs. We combine smart tools with human insight 
  to ensure every workflow, message, and customer experience is seamless and results-driven.
  
  ExactWorx—Exactly What Works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ExactWorx.com" # the base hostname & protocol for your site
twitter_username: ExactWorx
github_username:  ExactWorx

# Build settings
markdown: kramdown
